//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackRecruiter
    {
        public int FeedbackRecruiterID { get; set; }
        public string StudentID { get; set; }
        public int RecruiterID { get; set; }
        public string Content { get; set; }
    
        public virtual Recruiter Recruiter { get; set; }
        public virtual Student Student { get; set; }
    }
}
