//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruiterReport
    {
        public int RecruiterReportID { get; set; }
        public int RecruiterID { get; set; }
        public string RecruiterName { get; set; }
        public int RateID { get; set; }
    
        public virtual Rate Rate { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
