//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int SkillID { get; set; }
        public string SkillName { get; set; }
        public int DepartmentID { get; set; }
        public string StudentID { get; set; }
        public int StudentAspirationsID { get; set; }
        public int JobID { get; set; }
        public int ExperienceID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Experience Experience { get; set; }
        public virtual Job Job { get; set; }
        public virtual Student Student { get; set; }
        public virtual StudentAspiration StudentAspiration { get; set; }
    }
}
