//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSkill
    {
        public int JobSkillsID { get; set; }
        public Nullable<int> SkillID { get; set; }
        public Nullable<int> JobID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
