//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAspiration
    {
        public int UserAspirationID { get; set; }
        public int AspirationsID { get; set; }
        public int UserID { get; set; }
    
        public virtual Aspiration Aspiration { get; set; }
        public virtual User User { get; set; }
    }
}
