//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class User
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public User()
		{
			this.Feedbacks = new HashSet<Feedback>();
			this.Feedbacks1 = new HashSet<Feedback>();
			this.HistoryRecords = new HashSet<HistoryRecord>();
			this.InterviewSchedules = new HashSet<InterviewSchedule>();
			this.InterviewSchedules1 = new HashSet<InterviewSchedule>();
			this.Jobs = new HashSet<Job>();
			this.Notifications = new HashSet<Notification>();
			this.Notifications1 = new HashSet<Notification>();
			this.Rates = new HashSet<Rate>();
			this.Rates1 = new HashSet<Rate>();
			this.Reports = new HashSet<Report>();
			this.Reports1 = new HashSet<Report>();
			this.Statisticals = new HashSet<Statistical>();
			this.UserAspirations = new HashSet<UserAspiration>();
			this.UserJobs = new HashSet<UserJob>();
			this.UserRoles = new HashSet<UserRole>();
		}

		public int UserID { get; set; }
		[Required(ErrorMessage = "Nhập tên tài khoản.")]
		public string Username { get; set; }
		[Required(ErrorMessage = "Nhập mật khẩu.")]
		[DataType(DataType.Password)]
		public string Password { get; set; }
		public string Name { get; set; }
		public Nullable<int> Phone { get; set; }
		public Nullable<System.DateTime> DOB { get; set; }
		public Nullable<bool> Gender { get; set; }
		public string Email { get; set; }
		public Nullable<int> LocationID { get; set; }
		public Nullable<System.DateTime> CreateDate { get; set; }
		public string CV { get; set; }
		public string Description { get; set; }
		public Nullable<int> ImageID { get; set; }
		public string Status { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Feedback> Feedbacks { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Feedback> Feedbacks1 { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<HistoryRecord> HistoryRecords { get; set; }
		public virtual Image Image { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<InterviewSchedule> InterviewSchedules { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<InterviewSchedule> InterviewSchedules1 { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Job> Jobs { get; set; }
		public virtual Location Location { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Notification> Notifications { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Notification> Notifications1 { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Rate> Rates { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Rate> Rates1 { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Report> Reports { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Report> Reports1 { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Statistical> Statisticals { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<UserAspiration> UserAspirations { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<UserJob> UserJobs { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<UserRole> UserRoles { get; set; }
	}
}
